name: Run tests

on:
  workflow_call:
jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
      - name: Install packages
        run: npm ci
      - name: Run tests
        run: npx vitest run
  lint:
    name: Run linter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
      - name: Install packages
        run: npm ci
      - name: Lint with ESLint
        run: npm run lint
  format:
    name: Check format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
      - name: Install packages
        run: npm ci
      - name: Format check with prettier
        run: npm run prettier:check:ci

